apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    foo: bar
  name: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /healthy
            port: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 1.5G
